wip - investigation of TypeError in test runner
Running the following test:

yarn test:unit tests/unit/portalData/store.spec.ts

Fails with the following error:

yarn run v1.22.19
$ vue-cli-service test:unit tests/unit/portalData/store.spec.ts
 FAIL  tests/unit/portalData/store.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'getters')

      180 | };
      181 |
    > 182 | export const store = createStore<RootState>({
          |                                 ^
      183 |   strict: process.env.NODE_ENV !== 'production',
      184 |   state: initialRootState,
      185 |   mutations,

      at forEach (node_modules/vuex/dist/vuex.cjs.js:876:19)
          at Array.forEach (<anonymous>)
      at assertRawModule (node_modules/vuex/dist/vuex.cjs.js:875:28)
      at ModuleCollection.register (node_modules/vuex/dist/vuex.cjs.js:776:5)
      at fn (node_modules/vuex/dist/vuex.cjs.js:790:16)
      at forEach (node_modules/vuex/dist/vuex.cjs.js:73:52)
          at Array.forEach (<anonymous>)
      at forEachValue (node_modules/vuex/dist/vuex.cjs.js:73:20)
      at ModuleCollection.register (node_modules/vuex/dist/vuex.cjs.js:789:5)
      at new ModuleCollection (node_modules/vuex/dist/vuex.cjs.js:750:8)
      at new Store (node_modules/vuex/dist/vuex.cjs.js:921:19)
      at createStore (node_modules/vuex/dist/vuex.cjs.js:899:10)
      at Object.<anonymous> (src/store/index.ts:182:33)
      at Object.<anonymous> (src/plugins/localize.ts:35:1)
      at Object.<anonymous> (src/jsHelper/portalCategories.ts:45:1)
      at Object.<anonymous> (src/store/modules/portalData/index.ts:36:1)
      at Object.<anonymous> (tests/unit/portalData/store.spec.ts:8:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.592 s, estimated 2 s
Ran all test suites matching /tests\/unit\/portalData\/store.spec.ts/i.
(node:12579) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.